name: "Pull Request Docs Check"
on: 
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
